routes/consultas.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from utils.db_con import connection

consultas = Blueprint('consultas',__name__)
consultas.secret_key="ScrtKy"

# ~~~~~~~~~~~~~~~~ Variables Globales ~~~~~~~~~~~~~~~~
inst=''
instancias={
    'sales': 'NEGA-PC',
    'production': 'NEGA-PC',
    'other': 'NEGA-PC'
}

# ~~~~~~~~~~~~~~~~ Métodos Auxiliares (Listas) ~~~~~~~~~~~~~~~~
def complete_SelCat():
    global instancias
    global inst
    categories = []
    conn = connection(inst)
    cursor = conn.cursor()
    cursor.execute("EXEC dbo.usp_CategoryList ?",instancias.get('production'))
    print(cursor)
    for row in cursor.fetchall():
        categories.append({"id": row[0], "name": row[1]})
    conn.close()
    return categories

def complete_SelProd():
    global instancias
    global inst
    products = []
    conn = connection(inst)
    cursor = conn.cursor()
    cursor.execute("EXEC dbo.usp_ProductList ?",instancias.get('production'))
    print(cursor)
    for row in cursor.fetchall():
        products.append({"id": row[0], "name": row[1]})
    conn.close()
    return products

def complete_SelReg():
    global instancias
    global inst
    regions = []
    conn = connection(inst)
    cursor = conn.cursor()
    cursor.execute("EXEC dbo.usp_RegionList ?",instancias.get('sales'))
    print(cursor)
    for row in cursor.fetchall():
        regions.append({"group": row[0]})
    conn.close()
    return regions

def complete_SelLoc():
    global instancias
    global inst
    locations = []
    conn = connection(inst)
    cursor = conn.cursor()
    cursor.execute("EXEC dbo.usp_LocationList ?",instancias.get('production'))
    print(cursor)
    for row in cursor.fetchall():
        locations.append({"id": row[0], "name": row[1]})
    conn.close()
    return locations

def complete_SelMet():
    global instancias
    global inst
    methods_u = []
    conn = connection(inst)
    cursor = conn.cursor()
    cursor.execute("EXEC dbo.usp_MethodList ?",instancias.get('other'))
    
    for row in cursor.fetchall():
        methods_u.append({"id": row[0], "name": row[1]})
    conn.close()
    return methods_u

def complete_SelTerr():
    global instancias
    global inst
    territories = []
    conn = connection(inst)
    cursor = conn.cursor()
    cursor.execute("EXEC dbo.usp_TerritoryList ?",instancias.get('other'))
    
    for row in cursor.fetchall():
        territories.append({"id": row[0], "name": row[1], "group": row[2]})
    conn.close()
    return territories


# ~~~~~~~~~~~~~~~~ Métodos Principales (render y controlers) ~~~~~~~~~~~~~~~~

@consultas.route("/") #For default route
def Index():
    return render_template("index.html")

@consultas.route("/listex", methods=['POST'])
def listex():
    global inst, instancias
    if request.method == 'POST':
        
        opt=request.form['Instancia']    
        
        if opt == '01':
            inst=instancias.get('sales')
        elif opt == '02':
            inst=instancias.get('production')
        elif opt == '03':
            inst=instancias.get('other')    
        
        return redirect(url_for('consultas.consulta'))

@consultas.route("/consulta")
def consulta():
    products = []
    global inst
    if inst == '':
        flash('Error en la instancia seleccionada')
        return redirect(url_for('consultas.Index'))
    conn = connection(inst)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM Production.product")
    for row in cursor.fetchall():
        products.append({"id": row[0], "name": row[1], "lsprice": row[2]})
    conn.close()
    return render_template("resultlist.html", products = products)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Consulta A
@consultas.route("/consulta_a")
def consulta_a():
    categories = complete_SelCat()
    return render_template('consulta_a.html', categories = categories)

@consultas.route("/consatrr", methods=['POST'])
def consatrr():
    global inst
    global instancias
    if request.method == 'POST':
        opt=request.form['Categoria']
        ventas = []
        if inst == '':
            flash('Error en la instancia seleccionada')
            return redirect(url_for('consultas.Index'))
        conn = connection(inst)
        cursor = conn.cursor()
        cursor.execute("EXEC dbo.usp_ConsATVTerr ?,?,?",opt,instancias.get('sales'),instancias.get('production'))
        
        for row in cursor.fetchall():
            ventas.append({"TerrName": row[0], "VentasTotales": row[1]})
        conn.close()
        categories = complete_SelCat()
        return render_template('consulta_a.html', ventas = ventas, categories = categories)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Consulta B
@consultas.route("/consulta_b")
def consulta_b():
    regions=complete_SelReg()
    return render_template('consulta_b.html', regions=regions)

@consultas.route("/consb", methods=['POST'])
def consb():
    global inst
    global instancias
    if request.method == 'POST':
        opt=request.form['Region']
        productos = []
        rowx=''
        if inst == '':
            flash('Error en la instancia seleccionada')
            return redirect(url_for('consultas.Index'))
        conn = connection(inst)
        cursor = conn.cursor()
        
        #Se obtiene el producto con el primer procedimiento
        cursor.execute("EXEC dbo.usp_ConsBProdSol ?,?,?",opt,instancias.get('sales'),instancias.get('production'))
        row=cursor.fetchone()
        rowx=str(row[2])
        print(rowx)
        #Se ejecuta otro query para obtener el valor del segundo procedimiento
        cursor.execute("EXEC dbo.usp_ConsBTerr ?,?,?",opt,str(rowx),instancias.get('sales'))
        row_f = cursor.fetchone()
        productos.append({"TVentas": row[0], "Name": row[1], "Id": row[2], "Region": opt, "Territory": row_f[0]})
        
        conn.close()
        regions=complete_SelReg()

        return render_template('consulta_b.html', productos = productos, regions = regions)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Consulta C
@consultas.route("/consulta_c")
def consulta_c():
    locations = complete_SelLoc()
    categories = complete_SelCat()
    return render_template('consulta_c.html', locations = locations, categories = categories)

@consultas.route("/consc", methods=['POST'])
def consc():
    global inst
    global instancias
    if request.method == 'POST':
        opt_cat=request.form['Categoria']
        opt_loc=request.form['Localidad']
        print(opt_cat+'   '+opt_loc)
        if not(opt_cat != '' and opt_loc != ''):
            flash('Formulario incompleto')
            return redirect(url_for('consultas.consulta_c'))
        conn = connection(inst)
        cursor = conn.cursor()
        cursor.execute("EXEC dbo.usp_ConsCUpdtProd ?,?,?",opt_loc,opt_cat,instancias.get('production'))
        row=cursor.fetchone()
        respuesta = row[0];
        conn.commit()
        conn.close()
        
        if respuesta == 'Success':
            flash('Valor Actualizado Correctamente')
            return redirect(url_for('consultas.consulta_c'))
        elif respuesta == 'NoProducts':
            flash('No hay Productos de esa Categoría en la Localidad.')
            return redirect(url_for('consultas.consulta_c'))

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Consulta D
@consultas.route("/consulta_d")
def consulta_d():
    territories = complete_SelTerr()
    return render_template('consulta_d.html', territories=territories)

@consultas.route("/consd", methods=['POST'])
def consd():
    global inst
    global instancias
    if request.method == 'POST':
        opt=request.form['Territorio']
        Usuarios = []
        if inst == '':
            flash('Error en la instancia seleccionada')
            return redirect(url_for('consultas.Index'))
        conn = connection(inst)
        cursor = conn.cursor()
        cursor.execute("EXEC usp_ConsDOrdTerrDis ?,?",opt,instancias.get('sales'))
        
        if cursor == None:
            flash('No se encontraron clientes con compras fuera de su territorio')
            return redirect(url_for('consultas.consulta_d'))
        else:
            print(cursor)
            for row in cursor.fetchall():
                Usuarios.append({"ID": row[0]})
            conn.close()
            territories = complete_SelTerr()
            return render_template('consulta_d.html', territories = territories, Usuarios=Usuarios)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Consulta E
@consultas.route("/consulta_e")
def consulta_e():
    products = complete_SelProd()
    return render_template('consulta_e.html', products = products)

@consultas.route("/conse", methods=['POST'])
def conse():
    global inst
    global instancias
    if request.method == 'POST':
        opt_ord=request.form['Orden']
        opt_pro=request.form['Producto']
        opt_can=request.form['Cantidad']
        if not(opt_can != '' and opt_ord != ''):
            flash('Formulario incompleto')
            return redirect(url_for('consultas.consulta_e'))
        conn = connection(inst)
        cursor = conn.cursor()
        cursor.execute("EXEC dbo.usp_ConsEUpdtSales ?,?,?,?,?",opt_can,opt_ord,opt_pro,instancias.get('sales'),instancias.get('production'))
        row=cursor.fetchone()
        respuesta = row[0];
        conn.commit()
        conn.close()
        print (opt_can+'  '+respuesta)
        if respuesta == 'Success':
            flash('Valor Actualizado Correctamente')
            return redirect(url_for('consultas.consulta_e'))
        elif respuesta == 'NoProducts':
            flash('No hay Suficientes Productos en Existencia.')
            return redirect(url_for('consultas.consulta_e'))

templates/calendar.html
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<input type="text" id="daterange" name="daterange" value="06/01/2011 - 12/31/2011" />

<script>
$(function() {
  $('input[name="daterange"]').daterangepicker({
    opens: 'left'
  }, function(start, end, label) {
    console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
  });
});
</script>

templates/consulta_a.html
{% include 'header.html' %}
<form id="formulario" method="post" action="/consatrr">

    <div class="card">
        <div class="card-header">
            Consulta A
        </div>
        <div class="card-body">
            <h5 class="card-title">Ventas Totales</h5>
            <p class="card-text">
                
                <div class="form-group">
                    <label for="Categoria">Seleccione la Categoría: </label>
                    <select id="Categoria" name="Categoria">
                        {% for category in categories %}
                            <option  value={{category.id}}>{{category.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <br/>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Buscar
                    </button>
                </div>

            </p>
        </div>
    </div>

</form>
<script></script>
<div id="tabla_a">
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Territorio</th>
            <th scope="col">Ventas Totales</th>
            </tr>
        </thead>
        <tbody>
            {% for venta in ventas %}
                <tr>
                    <td>{{ venta.TerrName }}</th>
                    <td>{{ venta.VentasTotales }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include 'footer.html' %}

templates/consulta_b.html
{% include 'header.html' %}
<form id="formulario" method="post" action="/consb">

    <div class="card">
        <div class="card-header">
            Consulta B
        </div>
        <div class="card-body">
            <h5 class="card-title">Producto más Vendido</h5>
            <p class="card-text">
                
                <div class="form-group">
                    <label for="Region">Seleccione la Región: </label>
                    <select id="Region" name="Region">
                        {% for region in regions %}
                            <option  value={{region.group}}>{{region.group}}</option>
                        {% endfor %}
                    </select>
                </div>
                <br/>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Buscar
                    </button>
                </div>

            </p>
        </div>
    </div>

</form>
<script></script>
<div id="tabla_b">
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Producto</th>
            <th scope="col">Ventas Totales</th>
            <th scope="col">Región</th>
            <th scope="col">Territorio</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
                <tr>
                    <td>{{ producto.Name }}</th>
                    <td>{{ producto.TVentas }}</td>
                    <td>{{ producto.Region }}</td>
                    <td>{{ producto.Territory }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include 'footer.html' %}

templates/consulta_c.html
{% include 'header.html' %}

{% with messages= get_flashed_messages() %}
{% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
            {{message}}
        {% endfor %}
    </div>
{% endif %}
{% endwith %}

<form id="formulario" method="post" action="/consc">

    <div class="card">
        <div class="card-header">
            Consulta C
        </div>
        <div class="card-body">
            <h5 class="card-title">Actualizar Inventario</h5>
            <p class="card-text">
                Seleccione la categoría de productos y la localidad dentro de las que se actualizara el inventario.
                <br/>
                <div class="form-group">
                    <label for="Categoria">Seleccione la Categoría: </label>
                    <select id="Categoria" name="Categoria">
                        {% for category in categories %}
                            <option  value={{category.id}}>{{category.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <br/>
                <div class="form-group">
                    <label for="Localidad">Seleccione la Localidad: </label>
                    <select id="Localidad" name="Localidad">
                        {% for location in locations %}
                            <option  value={{location.id}}>{{location.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Actualizar
                    </button>
                </div>
            </p>
        </div>
    </div>

</form>
{% include 'footer.html' %}

templates/consulta_d.html
{% include 'header.html' %}

{% with messages= get_flashed_messages() %}
{% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
            {{message}}
        {% endfor %}
    </div>
{% endif %}
{% endwith %}

<form id="formulario" method="post" action="/consd">

    <div class="card">
        <div class="card-header">
            Consulta D
        </div>
        <div class="card-body">
            <h5 class="card-title">Clientes con Compras fuera de tu reacción.</h5>
            <p class="card-text">
                Seleccione los trabajadores.
                <br/>
                <div class="form-group">
                    <label for="Territorio">Seleccione la Region: </label>
                    <select id="Territorio" name="Territorio">
                        {% for territory in territories %}
                            <option  value={{territory.id}}>{{territory.name}}:{{territory.group}}</option>
                        {% endfor %}
                    </select>
                </div>
                <br/>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Buscar
                    </button>
                </div>

            </p>
        </div>
    </div>

</form>
<script></script>
<div id="tabla_h">
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Usuario</th>
            </tr>
        </thead>
        <tbody>
            {% for user in Usuarios %}
                <tr>
                    <td>{{ user.id }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include 'footer.html' %}

templates/consulta_e.html
{% include 'header.html' %}

{% with messages= get_flashed_messages() %}
{% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
            {{message}}
        {% endfor %}
    </div>
{% endif %}
{% endwith %}

<form id="formulario" method="post" action="/conse">

    <div class="card">
        <div class="card-header">
            Consulta E
        </div>
        <div class="card-body">
            <h5 class="card-title">Actualizar en Orden</h5>
            <p class="card-text">
                Seleccione la orden a la cual hará la modificación y el producto de la misma.
                <br>Posteriormente ingrese la cantidad a añadir de piezas de ese producto.
                <br/>
                <div class="form-group">
                    <label for="Orden">Ingresa el número de Orden </label>
                    <input id="Orden" class="form-control" type="text" name="Orden">
                </div>
                <br/>
                <div class="form-group">
                    <label for="Producto">Seleccione el Producto: </label>
                    <select id="Producto" name="Producto">
                        {% for product in products %}
                            <option  value={{product.id}}>{{product.id}}:{{product.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <br>
                <div class="form-group">
                    <label for="Cantidad">Ingresa la cantidad</label>
                    <input id="Cantidad" class="form-control" type="text" name="Cantidad">
                </div>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Actualizar
                    </button>
                </div>

            </p>
        </div>
    </div>

</form>
{% include 'footer.html' %}

templates/consulta_f.html
{% include 'header.html' %}

{% with messages= get_flashed_messages() %}
{% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
            {{message}}
        {% endfor %}
    </div>
{% endif %}
{% endwith %}

<form id="formulario" method="post" action="/consf">

    <div class="card">
        <div class="card-header">
            Consulta F
        </div>
        <div class="card-body">
            <h5 class="card-title">Actualizar Método en una Orden</h5>
            <p class="card-text">
                Seleccionará el nuevo método a ingresar en la orden solicitada.
                <br/>
                <div class="form-group">
                    <label for="Metodo">Seleccione el Método: </label>
                    <select id="Metodo" name="Metodo">
                        {% for method_u in methods_u %}
                            <option  value={{method_u.id}}>{{method_u.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <br>
                <div class="form-group">
                    <label for="Orden">Ingresa el número de Orden </label>
                    <input id="Orden" class="form-control" type="text" name="Orden">
                </div>
                <br/>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Actualizar
                    </button>
                </div>
            </p>
        </div>
    </div>
</form>
{% include 'footer.html' %}

templates/consulta_g.html
{% include 'header.html' %}

{% with messages= get_flashed_messages() %}
{% if messages %}
    <div class="alert alert-danger" role="alert">
        {% for message in messages %}
            {{message}}
        {% endfor %}
    </div>
{% endif %}
{% endwith %}

<form id="formulario" method="post" action="/consg">

    <div class="card">
        <div class="card-header">
            Consulta G
        </div>
        <div class="card-body">
            <h5 class="card-title">Actualizar el correo de un cliente.</h5>
            <p class="card-text">
                Ingrese la id del cliente al que se le actualizara el correo
                <br/>
                <div class="form-group">
                    <label for="Customer">Ingresa la id del cliente </label>
                    <input id="Customer" class="form-control" type="text" name="Customer">
                </div>
                <br>
                <div class="form-group">
                    <label for="Email">Ingresa el nuevo email </label>
                    <input id="Email" class="form-control" type="email" name="Email" placeholder="name@example.com">
                </div>
                <br/>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Actualizar
                    </button>
                </div>
            </p>
        </div>
    </div>
</form>
{% include 'footer.html' %}

templates/consulta_i.html
{% include 'header.html' %}

<form id="formulario" method="post" action="/consi">

    <div class="card">
        <div class="card-header">
            Consulta I
        </div>
        <div class="card-body">
            <h5 class="card-title">Ventas Por Región</h5>
            <p class="card-text">
                Selecciona el rango de fechas en las que deseas conocer las ventas totales por región.
                <br/>
                <div class="form-group">
                    <label for="daterange">Seleccione las fechas: </label>
                    {% include 'calendar.html' %}
                </div>
                <br/>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Buscar
                    </button>
                </div>

            </p>
        </div>
    </div>

</form>
<script></script>
<div id="tabla_i">
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Región</th>
            <th scope="col">Ventas Totales</th>
            </tr>
        </thead>
        <tbody>
            {% for venta in ventas %}
                <tr>
                    <td>{{ venta.Region }}</th>
                    <td>{{ venta.VentasTotales }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% include 'footer.html' %}

templates/consulta_j.html
{% include 'header.html' %}

<form id="formulario" method="post" action="/consj">

    <div class="card">
        <div class="card-header">
            Consulta J
        </div>
        <div class="card-body">
            <h5 class="card-title">5 Productos Menos Vendidos</h5>
            <p class="card-text">
                Selecciona el rango de fechas en las que deseas conocer los productos menos vendidos por region.
                <br/>
                <div class="form-group">
                    <label for="daterange">Seleccione las fechas: </label>
                    {% include 'calendar.html' %}
                </div>
                <br/>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-cons">
                        Buscar
                    </button>
                </div>

            </p>
        </div>
    </div>

</form>
<script></script>
<div id="tabla_i">
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Producto</th>
            <th scope="col">Ventas</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
                <tr>
                    <td>{{ producto.Nombre }}</th>
                    <td>{{ producto.Ventas }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% include 'footer.html' %}

templates/footer.html
        
    </div>
    </body>
</html>

templates/header.html
<!DOCTYPE html>
<html>
    <head>
        <title>Example</title>
        <link rel="stylesheet" crossorigin="anonymous"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" >
            
            <script crossorigin="anonymous"
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" >
            </script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand">Práctica Fragmentación</a>
            <button class="navbar-toggler" data-target="#my-nav" data-toggle="collapse" aria-controls="my-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="my-nav" class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.Index')}}">Inicio</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_a')}}">Consulta a</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('consultas.consulta_b')}}" >Consulta b</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_c')}}">Consulta c</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_d')}}">Consulta d</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_e')}}">Consulta e</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_f')}}">Consulta f</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_g')}}">Consulta g</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_h')}}">Consulta h</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_i')}}">Consulta i</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('consultas.consulta_j')}}">Consulta j</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class = "container">
        

templates/index.html
{% include 'header.html' %}   
    
    {% with messages= get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-danger" role="alert">
                {% for message in messages %}
                    {{message}}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

    <br/>

    <h2>Generando Conexión</h2>
    <form id="formulario" method="post" action="/listex">

        <div class="card">
            <div class="card-header">
                Escoge la instancia a utilizar
            </div>
            <div class="card-body">
                <h5 class="card-title">Instancias</h5>
                <p class="card-text">
                    
                    <div class="form-group">
                        <label for="Instancia">Seleccione la instancia</label>
                        <select id="Instancia" name="Instancia">
                            <option  value="01">Ventas</option>
                            <option  value="02">Producción</option>
                            <option  value="03">Otros</option>
                        </select>
                    </div>
                    <br/>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">
                            Iniciar Conexión
                        </button>
                    </div>

                </p>
            </div>
        </div>

    </form>
{% include 'footer.html' %}

templates/resultlist.html
{% include 'header.html' %}
    <h2>Product List</h2>
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Product</th>
            <th scope="col">List Price</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</th>
                    <td>{{ product.name }}</td>
                    <td>{{ product.lsprice }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% include 'footer.html' %}